spring:
  test: "Prod-test"
aws:
  s3:
    bucket:
      landing: ${LANDING_BUCKET}
      logging: ${LOGGING_BUCKET_NAME}
    key:
      youtube: ${YOUTUBE_BUCKET_KEY}
      logging: ${LOGGING_BUCKET_KEY}
      title: ${TITLE_BUCKET_KEY}
      tags: ${TAGS_BUCKET_KEY}
youtube:
  api:
    clientid: ${CLIENT_ID}
    clientsecret: ${CLIENT_SECRET}
    authuri: ${AUTH_URI}
    tokenuri: ${TOKEN_URI}
    certurl: ${AUTH_PROVIDER_CERT_URL}
    redirecturi: ${REDIRECT_URI}
    refresh:
      token: ${YOUTUBE_REFRESH_TOKEN}